id: P008195
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD445
  title: བྱང་ཆུབ་ལམ་རིམ་ཁྲིད་ཡིག་སྐོར་དཔེ་རྙིང་དཔེ་དཀོན།
  author: ''
  volumes:
    45f9f87db59c419abfcdfc55003d39a0:
      image_group_id: I3PD1189
      title: ''
      volume_number: 1
      total_pages: 364
    027111bb77ae4488b9a87596993ed5f7:
      image_group_id: I3PD1190
      title: ''
      volume_number: 2
      total_pages: 790
